# Source: https://cloud.google.com/kubernetes-engine/docs/how-to/stateful-apps
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset
spec:
  selector:
    matchLabels:
      app: express-db-persistent
  serviceName: express-db-persistent-service
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: express-db-persistent
    spec:
      containers:
      - name: express-backend-sha256-1
        image: ...
        ports:
        - containerPort: 80
          name: stateful-port
        volumeMounts:
        - name: persistent-volume-express
          mountPath: ...
  volumeClaimTemplates:
  - metadata:
      name: persistent-volume-express
      annotations:
        ...
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi